[tool.ruff]
select = ["E", "F", "W", "I", "N", "YTT", "ANN", "S", "BLE", "B", "A", "EXE", "INP", "PIE", "T20", "PT", "Q", "SIM", "ARG", "PTH", "PGH", "RUF"]
ignore = ["ANN101", "ANN401", "S101", "SIM118", "RUF005"]
line-length = 120

[tool.ruff.per-file-ignores]
"scripts/sort_readme.py" = ["INP001"]

[tool.ruff.pep8-naming]
classmethod-decorators = ["classmethod", "classproperty"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.pycodestyle]
max-doc-length = 120

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
line-length = 120
skip-string-normalization = false

[tool.isort]
atomic = true
profile = "black"
line_length = 120
lines_before_imports = 1
